export type ToolName =
  | "WindowLevel"
  | "Pan"
  | "Zoom"
  | "Length"
  | "RectangleROI"
  | "EllipticalROI"
  | "CircleROI"
  | "FreehandROI"
  | "ArrowAnnotate"
  | "Probe"
  | "Angle"
  | "Bidirectional"
  | "PlanarFreehandROI"
  | "CobbAngle"
  | "RectangleROIStartEndThreshold"
  | "RectangleROIThreshold"
  | "SplineROI"
  | "LivewireContour"
  | "Magnify"
  | "ReferenceLines"
  | "OverlayGrid"
  | "Crosshairs"
  | "ScaleOverlay"
  | "AdvancedMagnify"
  | "UltrasoundDirectional"
  | "RectangleScissors"
  | "CircleScissors"
  | "SphereScissors"
  | "Label"
  | "DeleteAnnotation";

export const getToolDisplayName = (toolName: string): string => {
  switch (toolName) {
    case "WindowLevel":
      return "窗位/窗宽";
    case "Pan":
      return "平移";
    case "Zoom":
      return "缩放";
    case "Length":
      return "测量长度";
    case "RectangleROI":
      return "矩形标注";
    case "EllipticalROI":
      return "椭圆标注";
    case "CircleROI":
      return "圆形标注";
    case "FreehandROI":
      return "自由画线";
    case "ArrowAnnotate":
      return "箭头标注";
    case "Probe":
      return "探针";
    case "Angle":
      return "角度测量";
    case "Bidirectional":
      return "双向测量";
    case "PlanarFreehandROI":
      return "平面自由绘制";
    case "CobbAngle":
      return "Cobb角度测量";
    case "RectangleROIStartEndThreshold":
      return "矩形阈值标注";
    case "RectangleROIThreshold":
      return "矩形阈值工具";
    case "SplineROI":
      return "样条线标注";
    case "LivewireContour":
      return "活线轮廓";
    case "Magnify":
      return "放大镜";
    case "ReferenceLines":
      return "参考线";
    case "OverlayGrid":
      return "网格覆盖";
    case "Crosshairs":
      return "十字线";
    case "ScaleOverlay":
      return "比例尺";
    case "AdvancedMagnify":
      return "高级放大镜";
    case "UltrasoundDirectional":
      return "超声方向工具";
    case "RectangleScissors":
      return "矩形剪切";
    case "CircleScissors":
      return "圆形剪切";
    case "SphereScissors":
      return "球形剪切";
    case "Label":
      return "文字标注";
    case "DeleteAnnotation":
      return "删除标注";
    default:
      return toolName;
  }
};

export const getToolInstructions = (toolName: string): string => {
  switch (toolName) {
    case "WindowLevel":
      return "拖动鼠标调节亮度和对比度";
    case "Pan":
      return "拖动鼠标移动图像";
    case "Zoom":
      return "拖动鼠标缩放图像";
    case "Length":
      return "点击两点测量距离";
    case "RectangleROI":
      return "拖动画出矩形区域";
    case "EllipticalROI":
      return "拖动画出椭圆区域";
    case "CircleROI":
      return "拖动画出圆形区域";
    case "FreehandROI":
      return "拖动鼠标自由画线";
    case "ArrowAnnotate":
      return "点击两点放置箭头标注";
    case "Probe":
      return "点击查看像素值";
    case "Angle":
      return "点击三点测量角度";
    case "Bidirectional":
      return "拖动测量两个方向的距离";
    case "PlanarFreehandROI":
      return "拖动鼠标平面自由绘制";
    case "CobbAngle":
      return "测量Cobb角，常用于脊柱弯曲分析";
    case "RectangleROIStartEndThreshold":
      return "画矩形区域并设置阈值范围";
    case "RectangleROIThreshold":
      return "矩形阈值分割工具";
    case "SplineROI":
      return "绘制样条曲线区域";
    case "LivewireContour":
      return "智能边缘检测轮廓绘制";
    case "Magnify":
      return "点击显示局部放大镜";
    case "ReferenceLines":
      return "显示切面参考线";
    case "OverlayGrid":
      return "显示网格覆盖层";
    case "Crosshairs":
      return "显示十字线定位";
    case "ScaleOverlay":
      return "显示比例尺标记";
    case "AdvancedMagnify":
      return "高级放大镜功能";
    case "UltrasoundDirectional":
      return "超声图像方向标注";
    case "RectangleScissors":
      return "矩形区域剪切工具";
    case "CircleScissors":
      return "圆形区域剪切工具";
    case "SphereScissors":
      return "球形区域剪切工具";
    case "Label":
      return "点击插入文字标注";
    case "DeleteAnnotation":
      return "删除当前选中的标注";
    default:
      return "选择工具进行操作";
  }
};
